version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  build-node-project:
    
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm start

workflows:
  my-custom-workflow:
    jobs:
      - build-node-project